# Generated by Django 4.2.4 on 2023-08-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_email_member_image_member_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='descpription',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='text',
            new_name='property_name',
        ),
        migrations.AddField(
            model_name='member',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
