# Generated by Django 4.2.4 on 2023-08-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_lastname_member_descpription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
