# Generated by Django 4.2.4 on 2023-08-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_descpription_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_model',
        ),
    ]
