# Generated by Django 4.2.4 on 2023-08-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='members'),
        ),
    ]
