# Generated by Django 4.2.4 on 2023-08-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='image',
            new_name='image_property',
        ),
    ]
